version: '3.9'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=leovegas-db
    ports:
      - "33006:3306"
    volumes:
      - ./local-data:/var/db/data